### ISSUE TITLE
Map to class instances

### ISSUE THREAD

**Issue by felixfbecker** [gamringer/JSONPatch#1]
Is there a way to make the patch apply with mapping the JSON `stdClass` object to the correct class instance?
I have been using https://github.com/cweiske/jsonmapper a lot and need this functionality for applying JSON patches. Basically I need the `apply()` function to figure out the type of the property at the JSON Pointer and then map the value to that type before applying.

**Comment by gamringer** [comment]
There is nothing in my library that allows for this out of the box, but I'll look into it, I will have a suggestion soon.

**Comment by gamringer** [comment]
Hi Felix, I am sorry for coming back to you only this late. I have looked at a way to implement this and realized that you can already achieve this using a feature from the underlying JSONPointer lib. You can create your own Accessors and adding them to the AccessorCollection object in the pointer. You can use JSONMapper inside your accessor to make the patch as modular as you want.

I am working on an example that I will add to the JSONPointer documentation. Do you think that would help ?

**Comment by felixfbecker** [comment]
An example would be great :)

**Comment by gamringer** [comment]
https://github.com/gamringer/JSONPointer/blob/master/examples/custom-accessor/index.php

Checkout this example. This is a basic example on how to use custom accessors, but for your specific use case, you can have an accessor where in the setValue() method, you put a check for a group of properties, and if the property being set is part of the group, you call a specific factory method to construct an object out of the array/stdObject of properties being passed.
